name: Lint, Format, Test & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  prepare-npm-cache-ubuntu:
    uses: ./.github/workflows/prepare-cache.yml
    with:
      os: ubuntu-latest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: prepare-npm-cache-ubuntu

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci --prefer-offline --no-audit --no-fund
      - run: npm run build
      - run: npm run lint

  test-ubuntu:
    uses: ./.github/workflows/test.yml
    needs: prepare-npm-cache-ubuntu
    with:
      os: ubuntu-latest

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - lint
      - test-ubuntu
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: npm ci --prefer-offline --no-audit --no-fund
      - run: npm audit signatures
      - run: npm run build
      - uses: changesets/action@v1
        with:
          publish: npm run release
          title: "chore(release): version packages"
          commit: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
