name: Prepare CI cache

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  prepare-yarn-cache:
    name: Prepare npm cache for ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Validate cache
        run: npm ci --prefer-offline --no-audit --no-fund
