name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]
        shard: ["1/4", "2/4", "3/4", "4/4"]
    name: Node v${{ matrix.node-version }} on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: run tests using jest
        run: npm run test -- --shard=${{ matrix.shard }}
